### ISSUE TITLE
Prediction crashes

### ISSUE THREAD

**Issue by leonweber** [aistairc/DeepEventMine#6]
I'm trying to generate predictions with the pertained models. On my end the command `sh run.sh pc predict gold dev` crashes with
```
Traceback (most recent call last):
  File "predict.py", line 113, in <module>
    main()
  File "predict.py", line 92, in main
    params=parameters)
  File "/home/leon/projects/DeepEventMine/eval/evaluate.py", line 64, in predict
    ner_out, rel_out, ev_out = model(tensors, params)
  File "/home/leon/anaconda3/envs/dem/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/leon/projects/DeepEventMine/nets/deepEM.py", line 296, in forward
    ner_preds, rel_preds, ev_preds = self.calculate(batch_input)
  File "/home/leon/projects/DeepEventMine/nets/deepEM.py", line 196, in calculate
    span_preds[span_idx] = e_golds[sentence_idx][span_idx]
IndexError: index 298 is out of bounds for axis 0 with size 2
```

**Comment by trieuhl** [comment]
Hi, thank you for your comment. I have fixed. Could you try again and let me know?

**Comment by leonweber** [comment]
Hey, thanks for the swift response and fix! The prediction works now, but there seems to be some offset error:

`python2 evaluation-PC.py -r data/original_corpora/pc/dev/ experiments/pc/predict-gold-dev/ev-last/ev-ann/*`

gives me 

```
------------------------------------------------------------------------------------
     Event Class          gold (match)   answer (match)   recall    prec.   fscore
------------------------------------------------------------------------------------
      Conversion            32 (    1)       26 (    1)     3.12     3.85     3.45
   Phosphorylation         168 (    7)      138 (    7)     4.17     5.07     4.58
  Dephosphorylation          4 (    0)        2 (    0)     0.00     0.00     0.00
     Acetylation            16 (    0)        7 (    0)     0.00     0.00     0.00
    Deacetylation            4 (    0)        0 (    0)     0.00     0.00     0.00
     Methylation             6 (    1)        4 (    1)    16.67    25.00    20.00
    Demethylation            0 (    0)        0 (    0)   100.00   100.00   100.00
    Ubiquitination          12 (    0)        8 (    0)     0.00     0.00     0.00
   Deubiquitination          0 (    0)        0 (    0)   100.00   100.00   100.00
     Localization           36 (    1)       29 (    1)     2.78     3.45     3.08
      Transport             56 (    0)       70 (    0)     0.00     0.00     0.00
   Gene_expression         125 (    0)      106 (    0)     0.00     0.00     0.00
    Transcription           16 (    0)       19 (    0)     0.00     0.00     0.00
     Translation             4 (    0)        0 (    0)     0.00     0.00     0.00
   =[SIMPLE-TOTAL]=        479 (   10)      409 (   10)     2.09     2.44     2.25
     Degradation            33 (    0)       29 (    0)     0.00     0.00     0.00
      Activation           117 (    0)      103 (    0)     0.00     0.00     0.00
     Inactivation           23 (    0)       14 (    0)     0.00     0.00     0.00
       Binding             216 (    3)      186 (    3)     1.39     1.61     1.49
     Dissociation           18 (    0)       12 (    0)     0.00     0.00     0.00
       Pathway             142 (    3)      132 (    3)     2.11     2.27     2.19
  ==[NONREG-TOTAL]==      1028 (   16)      885 (   16)     1.56     1.81     1.67
------------------------------------------------------------------------------------
      Regulation           228 (    7)      130 (    7)     3.07     5.38     3.91
 Positive_regulation       586 (    4)      381 (    4)     0.68     1.05     0.83
 Negative_regulation       287 (    4)      235 (    4)     1.39     1.70     1.53
   ==[REG-TOTAL]==        1101 (   15)      746 (   15)     1.36     2.01     1.62
------------------------------------------------------------------------------------
  ===[SUB-TOTAL]===       2129 (   31)     1631 (   31)     1.46     1.90     1.65
------------------------------------------------------------------------------------
       Negation             69 (    0)       38 (    0)     0.00     0.00     0.00
     Speculation            11 (    0)        2 (    0)     0.00     0.00     0.00
   ==[MOD-TOTAL]==          80 (    0)       40 (    0)     0.00     0.00     0.00
------------------------------------------------------------------------------------
   ====[TOTAL]====        2209 (   31)     1671 (   31)     1.40     1.86     1.60
------------------------------------------------------------------------------------
```

The predictions look reasonable but the trigger offsets don't seem to match often.

**Comment by trieuhl** [comment]
Hi, thank you for your respond.
For your result, you are running this command
python2 evaluation-PC.py -r data/original_corpora/pc/dev/ experiments/pc/predict-gold-dev/ev-last/ev-ann/*

The reason is that: you are comparing the original input offsets (data/original_corpora/..) with the tokenized predicted offsets (../ev-last/ev-ann/). There are two ways to solve this problem.
1, If you want to evaluate based on the tokenized offsets: the tokenized input is in "data/corpora/", so please change the "original_corpora" by "corpora"

2, If you want to evaluate based on the original offsets:
- First, you need to retrieve the original offsets for the predictions. This script is available in this repository by running the following command
sh run.sh pc eval gold dev
The output will be saved in the path: experiments/pc/predict-gold-dev/ev-last/ev-orig-a2/*
- Now you run your command, keeping the reference (original_corpora), but change the prediction into (..ev-last/ev-orig-a2/*), which is the retrieved offsets that we have run above.

Please try and let me know how it works.

**Comment by trieuhl** [comment]
Hi. I have updated the code which can do the evaluation that you mentioned. You may try again.

**Comment by leonweber** [comment]
It now works. Thanks a lot :)
