### ISSUE TITLE
error when importing torch

### ISSUE THREAD

**Issue by charliejeynes** [aistairc/DeepEventMine#9]
HI 

when I run  sh run.sh config cg 0 for the install I get this error

(pytorch-env) [cjeynes DeepEventMine]$ sh run.sh config cg 0
Traceback (most recent call last):
  File "scripts/generate_configs.py", line 7, in <module>
    from utils import utils
  File "./utils/utils.py", line 15, in <module>
    import torch
  File "/home/UK/cjeynes/git_repos/DeepEventMine/pytorch-env/lib/python3.7/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/UK/cjeynes/git_repos/DeepEventMine/pytorch-env/lib/python3.7/site-packages/torch/_C.cpython-37m-x86_64-linux-gnu.so)
Done!

but earlier on when I did 
(pytorch-env) [cjeynes DeepEventMine]$ export CUDA_VISIBLE_DEVICES=0
(pytorch-env) [cjeynes DeepEventMine]$ CUDA_PATH=/usr/local/cuda pip install torch==1.1.0 torchvision==0.3.0

it says requirement already satisfied (it installed fine on the first command)

is there an easy fix?

thanks

**Comment by trieuhl** [comment]
We have updated a new setting environment with conda here. Could you try again?
https://github.com/aistairc/DeepEventMine/tree/train
